import React, { useState, useRef } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { useStudyStore } from '../store/studyStore';
import { generateStudyNotes } from '../services/ai';
import { FileText, Sparkles, Loader2, Trash2, ChevronDown, Clock, BookOpen, Download, Plus, LayoutGrid, Library } from 'lucide-react';
import { jsPDF } from 'jspdf';
import { marked } from 'marked';

const SUBJECTS = [
  'Mathematics', 'Physics', 'Chemistry',  'Computer Science',
  'Biology', 'English', 'Electronics', 'Data Structures',
  'Engineering Drawing', 'Economics',
];

export default function StudyNotes() {
  const { savedNotes, saveNote, deleteNote, updateStats, addSubjectStudied } = useStudyStore();
  const [subject, setSubject] = useState('');
  const [topic, setTopic] = useState('');
  const [generatedNotes, setGeneratedNotes] = useState('');
  const [isGenerating, setIsGenerating] = useState(false);
  const [activeView, setActiveView] = useState('generate'); // 'generate' | 'saved'
  const [expandedNote, setExpandedNote] = useState(null);
  const notesContainerRef = useRef(null);

  const handleGenerate = async (e) => {
    e.preventDefault();
    if (!subject || !topic.trim()) return;

    setIsGenerating(true);
    setGeneratedNotes('');

    const notes = await generateStudyNotes(subject, topic);
    setGeneratedNotes(notes);
    setIsGenerating(false);

    updateStats({
      totalNotes: (useStudyStore.getState().studyStats.totalNotes || 0) + 1,
      totalStudyMinutes: (useStudyStore.getState().studyStats.totalStudyMinutes || 0) + 5,
    });
    addSubjectStudied(subject);
  };

  const handleSave = () => {
    if (!generatedNotes) return;
    saveNote({
      id: Date.now().toString(),
      subject,
      topic,
      content: generatedNotes,
      createdAt: new Date().toISOString(),
    });
    setGeneratedNotes('');
    setTopic('');
    setActiveView('saved');
  };

  const handleDownloadPDF = async () => {
    if (!generatedNotes) return;

    const htmlContent = marked.parse(generatedNotes);
    
    const tempDiv = document.createElement('div');
    tempDiv.innerHTML = `
      <div style="font-family: Arial, sans-serif; color: #1a1a1a; padding: 40px; line-height: 1.6;">
        <h1 style="color: #6366f1; margin-bottom: 5px;">EduMesh Study Material</h1>
        <p style="color: #666; margin-bottom: 30px;">${subject} &bull; ${topic}</p>
        <hr style="border: none; border-top: 1px solid #eee; margin-bottom: 30px;" />
        ${htmlContent}
        <footer style="margin-top: 50px; padding-top: 20px; border-top: 1px solid #eee; font-size: 10px; color: #999; text-align: center;">
          Generated by EduMesh AI on ${new Date().toLocaleDateString()}
        </footer>
      </div>
    `;
    tempDiv.style.width = '800px';
    document.body.appendChild(tempDiv);

    const doc = new jsPDF({
      orientation: 'portrait',
      unit: 'mm',
      format: 'a4'
    });

    await doc.html(tempDiv, {
      callback: function (doc) {
        doc.save(`${subject}_${topic.replace(/\s+/g, '_')}.pdf`);
        document.body.removeChild(tempDiv);
      },
      x: 10,
      y: 10,
      width: 190,
      windowWidth: 800
    });
  };

  const renderMarkdown = (text) => {
    return text.split('\n').map((line, i) => {
      if (line.startsWith('## ')) return <h2 key={i} className="text-lg font-bold mt-6 mb-3 flex items-center gap-2">{line.slice(3)}</h2>;
      if (line.startsWith('### ')) return <h3 key={i} className="text-base font-bold mt-4 mb-2 text-[#E8A2A2]">{line.slice(4)}</h3>;
      if (line.startsWith('- ') || line.startsWith('* ')) return <li key={i} className="ml-5 list-disc text-sm text-gray-600 dark:text-gray-400 leading-relaxed mb-2">{line.slice(2)}</li>;
      if (/^\d+\.\s/.test(line)) return <li key={i} className="ml-5 list-decimal text-sm text-gray-600 dark:text-gray-400 leading-relaxed mb-2">{line.replace(/^\d+\.\s/, '')}</li>;
      if (line.trim() === '') return <br key={i} />;

      const parts = line.split(/\*\*(.*?)\*\*/);
      const rendered = parts.map((part, j) =>
        j % 2 === 1 ? <strong key={j} className="font-bold text-gray-900 dark:text-white">{part}</strong> : part
      );
      return <p key={i} className="text-sm text-gray-600 dark:text-gray-400 leading-relaxed mb-2">{rendered}</p>;
    });
  };

  return (
    <div className="min-h-screen bg-[#f8fafc] dark:bg-[#050510]">
      <main className="max-w-6xl mx-auto px-6 py-8 sm:py-12">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          className="space-y-8"
        >
          {/* Header */}
          <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-6">
            <div className="space-y-1">
              <h1 className="text-3xl font-bold tracking-tight" style={{ fontFamily: 'Outfit, sans-serif' }}>Study Notes</h1>
              <p className="text-sm text-gray-400">Transform any topic into structured learning material.</p>
            </div>

            <div className="flex p-1 bg-black/5 dark:bg-white/5 rounded-2xl w-fit border border-gray-100 dark:border-white/5">
              <button
                onClick={() => setActiveView('generate')}
                className={`flex items-center gap-2 px-5 py-2.5 rounded-xl text-xs font-bold uppercase tracking-wider transition-all ${
                  activeView === 'generate' ? 'bg-white dark:bg-gray-800 text-[#E8A2A2] shadow-sm' : 'text-gray-400 hover:text-gray-600 dark:hover:text-gray-200'
                }`}
              >
                <Plus size={14} /> Generate
              </button>
              <button
                onClick={() => setActiveView('saved')}
                className={`flex items-center gap-2 px-5 py-2.5 rounded-xl text-xs font-bold uppercase tracking-wider transition-all ${
                  activeView === 'saved' ? 'bg-white dark:bg-gray-800 text-[#E8A2A2] shadow-sm' : 'text-gray-400 hover:text-gray-600 dark:hover:text-gray-200'
                }`}
              >
                <Library size={14} /> Library ({savedNotes.length})
              </button>
            </div>
          </div>

          <AnimatePresence mode="wait">
            {activeView === 'generate' ? (
              <motion.div
                key="generate"
                initial={{ opacity: 0, x: -20 }}
                animate={{ opacity: 1, x: 0 }}
                exit={{ opacity: 0, x: 20 }}
                className="space-y-8"
              >
                {/* Form */}
                <div className="m3-card shadow-lg bg-white dark:bg-gray-800">
                  <form onSubmit={handleGenerate} className="space-y-6">
                    <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                      <div className="space-y-2">
                        <label className="text-xs font-bold uppercase tracking-widest text-gray-400 ml-1">Subject</label>
                        <select
                          value={subject}
                          onChange={(e) => setSubject(e.target.value)}
                          className="input-field"
                          required
                        >
                          <option value="">Select subject...</option>
                          {SUBJECTS.map((s) => (
                            <option key={s} value={s}>{s}</option>
                          ))}
                        </select>
                      </div>
                      <div className="space-y-2">
                        <label className="text-xs font-bold uppercase tracking-widest text-gray-400 ml-1">Topic Name</label>
                        <input
                          type="text"
                          value={topic}
                          onChange={(e) => setTopic(e.target.value)}
                          placeholder="e.g. Quantum Entanglement"
                          className="input-field"
                          required
                        />
                      </div>
                    </div>
                    <button
                      type="submit"
                      disabled={isGenerating || !subject || !topic.trim()}
                      className="btn-primary w-full sm:w-auto"
                    >
                      {isGenerating ? (
                        <>
                          <Loader2 className="w-5 h-5 animate-spin" />
                          Synthesizing Core Concepts...
                        </>
                      ) : (
                        <>
                          <Sparkles className="w-5 h-5" />
                          Generate High-Quality Notes
                        </>
                      )}
                    </button>
                  </form>
                </div>

                {/* Skeleton */}
                {isGenerating && (
                  <div className="m3-card space-y-6 animate-pulse bg-white dark:bg-gray-800">
                    <div className="h-8 bg-gray-100 dark:bg-white/5 rounded-xl w-1/3" />
                    <div className="space-y-3">
                      <div className="h-4 bg-gray-100 dark:bg-white/5 rounded-lg w-full" />
                      <div className="h-4 bg-gray-100 dark:bg-white/5 rounded-lg w-5/6" />
                      <div className="h-4 bg-gray-100 dark:bg-white/5 rounded-lg w-4/6" />
                    </div>
                  </div>
                )}

                {/* Generated Content */}
                {generatedNotes && !isGenerating && (
                  <motion.div
                    initial={{ opacity: 0, y: 30 }}
                    animate={{ opacity: 1, y: 0 }}
                    className="m3-card shadow-2xl bg-white dark:bg-gray-800 !p-0 overflow-hidden"
                  >
                    <div className="p-8 border-b border-gray-100 dark:border-white/5 flex flex-col md:flex-row md:items-center justify-between gap-6 bg-[#E8A2A2]/5">
                      <div className="flex items-center gap-5">
                        <div className="w-14 h-14 rounded-3xl bg-[#E8A2A2] flex items-center justify-center shadow-lg shadow-[#E8A2A2]/20">
                          <FileText className="w-7 h-7 text-white" />
                        </div>
                        <div>
                          <h2 className="text-xl font-bold">{topic}</h2>
                          <p className="text-sm text-gray-500">{subject} &bull; Generated Study Material</p>
                        </div>
                      </div>
                      <div className="flex gap-3">
                        <button onClick={handleDownloadPDF} className="p-3 bg-white dark:bg-gray-700 text-gray-500 hover:text-[#E8A2A2] rounded-2xl border border-gray-100 dark:border-white/10 transition-all shadow-sm">
                          <Download size={20} />
                        </button>
                        <button onClick={handleSave} className="btn-primary">
                          Save to Library
                        </button>
                      </div>
                    </div>
                    <div className="p-8 sm:p-12 prose dark:prose-invert max-w-none prose-sm" ref={notesContainerRef}>
                      {renderMarkdown(generatedNotes)}
                    </div>
                  </motion.div>
                )}
              </motion.div>
            ) : (
              <motion.div
                key="saved"
                initial={{ opacity: 0, x: 20 }}
                animate={{ opacity: 1, x: 0 }}
                exit={{ opacity: 0, x: -20 }}
                className="grid grid-cols-1 gap-4"
              >
                {savedNotes.length === 0 ? (
                  <div className="m3-card text-center !py-24 bg-white dark:bg-gray-800">
                    <div className="w-20 h-20 rounded-full bg-gray-50 dark:bg-white/5 flex items-center justify-center mx-auto mb-6">
                      <Library className="w-10 h-10 text-gray-300" />
                    </div>
                    <p className="text-gray-500">Your library is empty.</p>
                    <button onClick={() => setActiveView('generate')} className="btn-primary mt-6 inline-flex">
                      Create Your First Note
                    </button>
                  </div>
                ) : (
                  savedNotes.map((note) => (
                    <div key={note.id} className="m3-card bg-white dark:bg-gray-800 !p-0 overflow-hidden group border-transparent hover:border-[#E8A2A2]/20">
                      <div
                        className="p-6 flex items-center justify-between cursor-pointer"
                        onClick={() => setExpandedNote(expandedNote === note.id ? null : note.id)}
                      >
                        <div className="flex items-center gap-5">
                          <div className="w-12 h-12 rounded-2xl bg-[#A0C2D2]/10 flex items-center justify-center shrink-0">
                            <FileText className="w-6 h-6 text-[#A0C2D2]" />
                          </div>
                          <div className="min-w-0">
                            <p className="font-bold truncate">{note.topic}</p>
                            <p className="text-xs text-gray-400 mt-1 flex items-center gap-2">
                              {note.subject} &bull; <Clock size={12} /> {new Date(note.createdAt).toLocaleDateString()}
                            </p>
                          </div>
                        </div>
                        <div className="flex items-center gap-3">
                          <button
                            onClick={(e) => { e.stopPropagation(); deleteNote(note.id); }}
                            className="p-2.5 rounded-xl hover:bg-red-500/10 text-gray-300 hover:text-red-500 transition-all opacity-0 group-hover:opacity-100"
                          >
                            <Trash2 size={18} />
                          </button>
                          <div className={`p-2 rounded-xl bg-gray-50 dark:bg-white/5 text-gray-400 transition-transform ${expandedNote === note.id ? 'rotate-180' : ''}`}>
                            <ChevronDown size={18} />
                          </div>
                        </div>
                      </div>

                      <AnimatePresence>
                        {expandedNote === note.id && (
                          <motion.div
                            initial={{ height: 0, opacity: 0 }}
                            animate={{ height: 'auto', opacity: 1 }}
                            exit={{ height: 0, opacity: 0 }}
                            className="overflow-hidden bg-gray-50/50 dark:bg-black/20"
                          >
                            <div className="p-8 sm:p-12 border-t border-gray-100 dark:border-white/5 prose prose-sm max-w-none">
                              {renderMarkdown(note.content)}
                            </div>
                          </motion.div>
                        )}
                      </AnimatePresence>
                    </div>
                  ))
                )}
              </motion.div>
            )}
          </AnimatePresence>
        </motion.div>
      </main>
    </div>
  );
}
